{% set name = "dye-score" %}
{% set version = "0.7.1" %}
{% set hash_type = "sha256" %}
{% set hash = "af336190e6d3cff54aa47b8ca0eeec0c5b5d4231212544410c3994227672ca5f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace("-", "_") }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - pytest
    - pytest-runner

  run:
    - python>=3
    - bokeh>=1.0.4
    - dask>=1.1.5
    - numpy>=1.14
    - pyarrow==0.12.1
    - pyyaml>=4.2b1
    - s3fs>=0.2.1
    - xarray>=0.12.0
    - zarr>=2.2.0

test:
  imports:
    - dye_score

about:
  home: https://pypi.python.org/pypi/dye-score
  license: MPL-2.0
  license_file: LICENSE
  summary: Utilities to build the dye-score metric from OpenWPM javascript call data.
  dev_url: https://github.com/mozilla/dye-score/
  doc_url: https://dyescore.readthedocs.io/

extra:
  recipe-maintainers:
    - birdsarah
