travis:
  secure:
    BINSTAR_TOKEN: F03vUL00CMbburuexDw10WKQ1daQXPDnJ5gEE+IzQOobwEh8mc9CWc7fCCChuUtRbOi/sGoDtagLtU5LF08dirw1whvoRsQ1xElO1e/Vi8DbqQXjJqxO9EyAVluFJPxyp+vlD2hFll382rn6DsrhwatgTtxbr0CGymvxsVc4fJBQVM8LDNDZi/cOpwD+aKDoV59yDnkYy9PwdUYKeCPziNUV0ZJAPeYbVN/i1y/ymq8SZHGeQVzxHGYSKHg5pCrfUZ5gVPbIMOMwV7MZPqwWudRRBREx3pWY5O5PSehsfz9rdwnGYsEGfDxWBKo00nF3tHQcaS0vZZWsqQsyqbtozr8WKJSdodf2qRVPq3PTvETPMJbjgdp6/4dcJYvT+gJKhiQ9LnqcZppnDB6fRVm7qCxaIYfBQETLtAqW5Ra5kO8TzGTP7uQ3iKG4f85dG0THlPFc8joIBLdLWC39aiFjzZZw7ks21b4sGyFMspvcaLGMzBmu7USaCGeNWIxoo8JOASgDoNjRqK96sg2FFQNHyHroO4w4bg1YthhUmCgluVOMXXtL3MWhPNev4ovufBeggtEX/ye9JzieqmdxAJYMZMFF/6P/RWv3I8gmzx48nqghyxt8cOYuSvA8B0Bk+Xs2WUvrcmRICnmUFNlfQtSbEhR68j1khKFMMFeoayJhYXg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
